export {
  getAlbumPhotos,
  getTrashPhotos,
  getPhotoDetails,
  updatePhotoTakenAt,
  updatePhotoMetadata,
  updatePhotoLocationHidden,
  toggleFavoritePhoto,
  getFavoritePhotos,
  setFavoritePhoto,
  softDeletePhoto,
  softDeletePhotos,
  batchSoftDeletePhotos,
  restorePhoto,
  restorePhotos,
  batchRestorePhotos,
  restoreTrashPhoto,
  restoreTrashPhotos,
  batchRestoreTrashPhotos,
  permanentlyDeletePhoto,
  batchPermanentlyDeletePhotos,
  permanentlyDeletePhotos,
  permanentlyDeleteTrashPhotos,
  batchPermanentlyDeleteTrashPhotos,
  batchSetFavoritePhotos,
  clearTrashPhotos,
} from "@/lib/media/library";
