export {
  getAlbumPhotos,
  getTrashPhotos,
  getPhotoDetails,
  updatePhotoTakenAt,
  toggleFavoritePhoto,
  getFavoritePhotos,
  softDeletePhoto,
  softDeletePhotos,
  restorePhoto,
  restorePhotos,
  restoreTrashPhotos,
  permanentlyDeletePhoto,
  permanentlyDeletePhotos,
  permanentlyDeleteTrashPhotos,
} from "@/lib/media/library";
